const express = require('express');

const healthRoutes = require('./health.routes');
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const startupRoutes = require('./startup.routes');
const communityRoutes = require('./community.routes');
const postRoutes = require('./post.routes');
const collaborationRoutes = require('./collaboration.routes');
const profileRoutes = require('./profile.routes');
const dashboardRoutes = require('./dashboard.routes');
const messageRoutes = require('./message.routes');
const notificationRoutes = require('./notification.routes');
const settingsRoutes = require('./settings.routes');
const searchRoutes = require('./search.routes');
const recommendationRoutes = require('./recommendation.routes');
const verificationRoutes = require('./verification.routes');
const adminRoutes = require('./admin.routes');
const teamRoutes = require('./team.routes');
const workspaceRoutes = require('./workspace.routes');
const projectRoutes = require('./project.routes');
const taskRoutes = require('./task.routes');
const milestoneRoutes = require('./milestone.routes');
const documentRoutes = require('./document.routes');
const jobRoutes = require('./job.routes');
const applicationRoutes = require('./application.routes');
const investorRoutes = require('./investor.routes');
const investmentInterestRoutes = require('./investmentInterest.routes');
const fundingRoundRoutes = require('./fundingRound.routes');
const fundingContributionRoutes = require('./fundingContribution.routes');
const providerProfileRoutes = require('./providerProfile.routes');
const serviceListingRoutes = require('./serviceListing.routes');
const engagementRequestRoutes = require('./engagementRequest.routes');
const analyticsRoutes = require('./analytics.routes');
const reportRoutes = require('./report.routes');
const aiRoutes = require('./ai.routes');

const router = express.Router();

router.use('/', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/startups', startupRoutes);
router.use('/communities', communityRoutes);
router.use('/posts', postRoutes);
router.use('/collaborations', collaborationRoutes);
router.use('/profile', profileRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/messages', messageRoutes);
router.use('/notifications', notificationRoutes);
router.use('/settings', settingsRoutes);
router.use('/search', searchRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/verification', verificationRoutes);
router.use('/admin', adminRoutes);
router.use('/teams', teamRoutes);
router.use('/workspaces', workspaceRoutes);
router.use('/projects', projectRoutes);
router.use('/tasks', taskRoutes);
router.use('/milestones', milestoneRoutes);
router.use('/documents', documentRoutes);
router.use('/jobs', jobRoutes);
router.use('/applications', applicationRoutes);
router.use('/investors', investorRoutes);
router.use('/investment-interests', investmentInterestRoutes);
router.use('/funding-rounds', fundingRoundRoutes);
router.use('/funding-contributions', fundingContributionRoutes);
router.use('/provider-profiles', providerProfileRoutes);
router.use('/service-listings', serviceListingRoutes);
router.use('/engagement-requests', engagementRequestRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/reports', reportRoutes);
router.use('/ai', aiRoutes);

module.exports = router;
